### ISSUE TITLE
README mentions PACKAGE_CANONICAL_SIMULATE_REMOTE, should be PACKAGE_CANONICAL_SIMULATE_PRODUCTION

### ISSUE THREAD

**Issue by jenschelkopf** [project-ricochet/meteor-canonical#1]
README mentions PACKAGE_CANONICAL_SIMULATE_REMOTE, but canonical_server.js uses PACKAGE_CANONICAL_SIMULATE_PRODUCTION.

**Comment by wizonesolutions** [comment]
Thanks for the report @jrullmann. `v0.0.4` fixes this and is published now.

**Comment by jenschelkopf** [comment]
Thanks, but I'm having a problem installing this package now.  I get this error when I try:

✓ canonical
    tag: https://github.com/projectricochet/meteor-canonical.git#v0.0.4

/usr/local/lib/node_modules/meteorite/lib/sources/git.js:151
hrow "There was a problem checking out " + self.checkoutType + ": " + (self.co

I think the problem is that there is no tag 0.0.4 in github.

**Comment by caseycobb** [comment]
Hi there, we were having this same problem on our app and I just pushed a
new tag.

Try again?

Best,
Casey

## 

Casey Cobb
Partner / Developer
Project Ricochet
www.projectricochet.com

Mobile: 925.270.4935

**Comment by jenschelkopf** [comment]
Works great, thanks so much!
