### ISSUE TITLE
This webpage has a redirect loop

### ISSUE THREAD

**Issue by isAlmogK** [project-ricochet/meteor-canonical#6]
I'm running into a redirect loop. I have the following ROOT_URL set https://linklyapp.com/

My app is hosted on modulus.io and the domain is set to linklyapp.com

**Comment by isAlmogK** [comment]
I tried testing it locally with PACKAGE_CANONICAL_DISABLE=true ROOT_URL=https://linklyapp.com meteor 

And I still get the redirect loop issue

**Comment by wizonesolutions** [comment]
Did removing the package fix the issue? It doesn't seem like it would be caused by this package at first glance. Do you get the same issue with `force-ssl`? This package was originally based off that, but it looks like the `force-ssl` code is still similar to how it was originally.

**Comment by isAlmogK** [comment]
@wizonesolutions I ended up moving my domain provider from GoDaddy to Hover and setting the naked domain via the DNS Zone file. I do think there was a plan to update the package and fix this issue.

**Comment by wizonesolutions** [comment]
@almogdesign Yeah, that is me :) — OK, if you aren't able to test any longer, that is OK. We'll see if anyone else reports the problem.
