### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by artiparty** [project-ricochet/meteor-canonical#7]
Guys, can you add an explanation how am I supposed to install Canonical?

**Comment by wizonesolutions** [comment]
It's a Meteor package. If you can't find it on Atmosphere (which would have the installation command), then it hasn't been ported to the new Meteor package system and is not installable in the latest versions of Meteor.

**Comment by projectricochet** [comment]
Hi Artiom,

Does this help at all? https://atmospherejs.com/wizonesolutions/canonical

Have you tried "$ meteor add wizonesolutions:canonical"?

Best,
Casey

## 

Casey Cobb
Partner / Developer
Project Ricochet
www.projectricochet.com

Mobile: 925.270.4935

**Comment by artiparty** [comment]
Thanks guys, it worked for me.

I guess it'll be great if you write on GitHub page something like:

_Installation:_

_"$ meteor add wizonesolutions:canonical"_

If it doesn't work it seems like your ROOT_URL is not set:

ROOT_URL=http://yourdomain.com meteor
