### ISSUE TITLE
Not redirecting 

### ISSUE THREAD

**Issue by isAlmogK** [project-ricochet/meteor-canonical#8]
Everything is working expect if with https://www.mydomain.com it gets stuck on the SSL cert not having one for www? Any ideas way this is happing

**Comment by wizonesolutions** [comment]
That's a browser thing, and there is nothing we can do about it :(

Also, many certificate vendors will give you a certificate that has SNI for both www and non-www. You have to request one for www. Ask your vendor if they do this and if you can get a reissue if so.
