### ISSUE TITLE
Multilanguage setup

### ISSUE THREAD

**Issue by jakobloekke** [project-ricochet/meteor-canonical#9]
Is it possible to use this package for a multilanguage site?

Right now we use meteor-canonical for ssl/seo redirection from 'http://site.dk' to 'https://www.site.dk'
We now need to alternate between languages based on the .domain suffix in the address (eg. .co.uk, .pl, .dk). 
So 'http://site.dk' should go to 'https://www.site.dk', 'http://site.co.uk' to 'https://www.site.co.uk' etc.

Is this event possible with a single server installation?

**Comment by wizonesolutions** [comment]
@jakobloekke Not right now, in any case. How are you handling `ROOT_URL` at each address? If you have already solved that problem, then maybe that'll be a hint to how to solve it within this package.

**Comment by jakobloekke** [comment]
I haven't solved that problem, sadly. Actually we've opted to run separate installations for each language, meaning each have their own ROOT_URL and language parameters. They just share the same database.
It works – but it feels like a very naive solution to this problem.

**Comment by hrhitesh** [comment]
@jakobloekke  can you share your code that how you use this package to write canonical url in head tag?

**Comment by wizonesolutions** [comment]
My impression is that right now it's best to use reverse-proxying to accomplish this.
